from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from scripts.utils.paths import project_root, safe_name
from scripts.utils.plot_style import PALETTE, apply_plot_style, polish_axis, save_figure


PHASE_COLORS = {
    "lag": "#6B7280",
    "exponential": PALETTE["primary"],
    "stationary": PALETTE["secondary"],
    "decline": PALETTE["danger"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot examples of synthetic microalgae growth cycles.")
    parser.add_argument(
        "--input",
        type=str,
        default="data/processed/synthetic_growth_cycles_OD.csv",
        help="Synthetic cycles CSV generated by the pipeline.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="outputs/figures/synthetic_examples",
        help="Directory for generated figures.",
    )
    parser.add_argument("--target", type=str, default=None, help="Optional target filter, for example OD.")
    parser.add_argument("--n-cycles", type=int, default=12, help="Number of cycles to overlay.")
    parser.add_argument("--cycle-id", type=str, default=None, help="Specific cycle_id to plot by phase.")
    parser.add_argument("--no-svg", action="store_true", help="Only save PNG files.")
    return parser.parse_args()


def main() -> None:
    root = project_root()
    args = parse_args()
    input_path = _resolve(root, args.input)
    output_dir = _resolve(root, args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    cycles = pd.read_csv(input_path)
    _validate_columns(cycles, input_path)
    if args.target:
        cycles = cycles[cycles["target"].astype(str).eq(args.target)].copy()
    if cycles.empty:
        raise ValueError(f"No synthetic cycles available after filtering: {input_path}")

    apply_plot_style()
    make_svg = not args.no_svg
    _plot_overlay(cycles, output_dir, args.n_cycles, make_svg)
    _plot_phases(cycles, output_dir, args.cycle_id, make_svg)
    print(f"Synthetic example figures saved in: {output_dir}")


def _plot_overlay(cycles: pd.DataFrame, output_dir: Path, n_cycles: int, make_svg: bool) -> None:
    import matplotlib.pyplot as plt  # type: ignore

    cycle_ids = cycles["cycle_id"].drop_duplicates().head(max(1, n_cycles))
    sample = cycles[cycles["cycle_id"].isin(cycle_ids)].copy()
    target = str(sample["target"].dropna().iloc[0]) if "target" in sample and sample["target"].notna().any() else "value"

    fig, ax = plt.subplots(figsize=(11.5, 6.0))
    for cycle_id, frame in sample.groupby("cycle_id", sort=False):
        frame = frame.sort_values("relative_time")
        ax.plot(
            frame["relative_time"],
            frame["value"],
            linewidth=2.0,
            alpha=0.72,
            label=str(cycle_id),
        )
    polish_axis(
        ax,
        f"Ejemplos de ciclos sinteticos de entrenamiento ({target})",
        "Tiempo relativo del ciclo",
        f"{target} simulado",
        legend=True,
    )
    ax.legend(ncol=3, frameon=False, fontsize=8)
    save_figure(fig, output_dir / f"{safe_name(target)}_synthetic_cycle_overlay", make_png=True, make_svg=make_svg)
    plt.close(fig)


def _plot_phases(cycles: pd.DataFrame, output_dir: Path, cycle_id: str | None, make_svg: bool) -> None:
    import matplotlib.pyplot as plt  # type: ignore

    selected = cycle_id or str(cycles["cycle_id"].drop_duplicates().iloc[0])
    cycle = cycles[cycles["cycle_id"].astype(str).eq(selected)].sort_values("relative_time")
    if cycle.empty:
        raise ValueError(f"cycle_id not found: {selected}")
    target = str(cycle["target"].dropna().iloc[0]) if "target" in cycle and cycle["target"].notna().any() else "value"

    fig, ax = plt.subplots(figsize=(10.5, 5.6))
    for phase, frame in cycle.groupby("phase", sort=False):
        ax.plot(
            frame["relative_time"],
            frame["value"],
            marker="o",
            markersize=5,
            linewidth=2.6,
            color=PHASE_COLORS.get(str(phase), PALETTE["muted"]),
            label=str(phase),
        )
    polish_axis(
        ax,
        f"Ciclo sintetico por fases: {selected}",
        "Tiempo relativo del ciclo",
        f"{target} simulado",
        legend=True,
    )
    save_figure(fig, output_dir / f"{safe_name(target)}_{safe_name(selected)}_phases", make_png=True, make_svg=make_svg)
    plt.close(fig)


def _resolve(root: Path, value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else root / path


def _validate_columns(cycles: pd.DataFrame, input_path: Path) -> None:
    required = {"cycle_id", "relative_time", "value", "phase"}
    missing = sorted(required - set(cycles.columns))
    if missing:
        raise ValueError(f"{input_path} is missing required columns: {missing}")


if __name__ == "__main__":
    main()
